name: Validate ESPHome Config

on:
  pull_request:
    branches: [main]
  push:
    branches-ignore: [main]

jobs:
  validate:
    name: ESPHome Config Validate
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/esphome/esphome:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare secrets
        run: cp secrets.example.yaml secrets.yaml

      - name: Validate ESPHome config
        run: esphome config esp32s3box3.yaml
